### PR TITLE
refactor(embed): generate font subset for embed

### PR DESCRIPTION
**Pull request by HenrikFricke**
I generated a subset of our font for the embed tool to minimize the file size and get independent from Google. What do you think @andrew-secret? Right now, the generation of the font is a manual step. If we need to do it more often, then we could also automate it. 

Replacing the fonts on the website is out of scope for this pull request. 

I also enabled bundle optimization, so we minify our code. The result: 

Before: 

image

After: 

image

### CODE REVIEW

**Comment by HenrikFricke** [comment]
Ah foo, but now the example project is also minfied :D

**Comment by andrew-secret** [comment]
Looks good to me expect of one little thing.

the bundle optimazation bundles the css example too 😅
image

**Comment by HenrikFricke** [comment]
Yeah, need to fix that 😂

**Comment by HenrikFricke** [comment]
Okay so I kicked the optimization, but I would love to introduce some form of optimization in another pull request.

**Pull request merged**
